"""Generate standalone artifacts from a workflow graph.

* :func:`workflow_to_script` emits a runnable ``.py`` file (library mode — it
  imports the ``noodle`` runtime).
* :func:`docker_bundle` emits the files needed to ship the workflow as an image.
"""

import json
import re

_SCRIPT_TEMPLATE = '''"""Noodle workflow: __NAME__

Generated by Noodle. Run with:  python __SLUG__.py
Requires: noodle-core and noodle-nodes (plus your environment packages).
"""

import noodle_nodes  # noqa: F401 - registers the built-in nodes
from noodle.engine import run
from noodle.models import WorkflowGraph
from noodle.sdk import registry

GRAPH = __GRAPH__


def main() -> None:
    result = run(WorkflowGraph.model_validate(GRAPH), registry)
    print(f"workflow finished: {result.status}")
    for node_id, node in result.nodes.items():
        print(f"  {node_id}: {node.status}")
        if node.error:
            print(f"    error: {node.error}")


if __name__ == "__main__":
    main()
'''

_DOCKERFILE_TEMPLATE = """FROM python:__PYVER__-slim

WORKDIR /workflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY workflow.py .

CMD ["python", "workflow.py"]
"""

_README_TEMPLATE = """# __NAME__

A Noodle workflow packaged as a Docker image.

```sh
docker build -t __SLUG__ .
docker run --rm __SLUG__
```
"""


def slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "workflow"


def workflow_to_script(graph: dict, name: str) -> str:
    """Render a workflow graph as a standalone Python script."""
    return (
        _SCRIPT_TEMPLATE.replace("__NAME__", name)
        .replace("__SLUG__", slugify(name))
        .replace("__GRAPH__", json.dumps(graph, indent=2))
    )


def docker_bundle(
    graph: dict,
    name: str,
    *,
    python_version: str = "3.12",
    packages: list[str] | None = None,
) -> dict[str, str]:
    """Render the file set needed to build and run the workflow as an image."""
    requirements = ["noodle-core", "noodle-nodes", *(packages or [])]
    return {
        "workflow.py": workflow_to_script(graph, name),
        "requirements.txt": "\n".join(requirements) + "\n",
        "Dockerfile": _DOCKERFILE_TEMPLATE.replace("__PYVER__", python_version),
        "README.md": _README_TEMPLATE.replace("__NAME__", name).replace(
            "__SLUG__", slugify(name)
        ),
    }
