"""Generate a code-first Python module from a workflow graph (export v2).

Unlike :func:`noodle_exporter.codegen.workflow_to_script` (which embeds the
graph as JSON), this emits one ``@node``-decorated function per workflow
node. The function's keyword defaults are the node's configured params,
``wires={...}`` declares its incoming edges, and the body delegates to the
built-in implementation so each node can be called standalone. ``main()``
reassembles the ``WorkflowGraph`` from the functions and runs it through the
Noodle engine — execution semantics are identical to running inside Noodle.
"""

import json
import keyword
import re

from noodle.models import GraphNode, WorkflowGraph

from .codegen import slugify

_DEFAULT_NODE_FIELDS = GraphNode(id="_", type="_").model_dump(exclude={"id", "type", "params"})

_HEADER_TEMPLATE = '''"""Noodle workflow: __NAME__ (code-first export)

Generated by Noodle. Run with:  python __SLUG__.py
Requires: noodle-core and noodle-nodes (plus your environment packages).

Each workflow node is a decorated function below.

* Editing a function\'s KEYWORD DEFAULTS changes the node\'s configuration
  (main() reads params back off the signatures).
* Editing ``wires={...}`` changes the graph\'s edges.
* Editing a generated function\'s BODY does NOT change the engine-driven run
  for these delegate wrappers — the engine executes the original built-in
  node type (see _DELEGATES). The body exists so you can call the node
  directly, e.g. ``fetch(url="https://...")``, for testing.
* Adding a NEW @node function with a fresh id (and not adding it to
  _DELEGATES) registers a real custom node the engine executes directly;
  wire it in via its ``wires={...}``.
"""

import inspect

import noodle_nodes  # noqa: F401 - registers the built-in nodes
from noodle.engine import run
from noodle.engine.subworkflows import InlineSubworkflow, SubworkflowMeta
from noodle.models import WorkflowGraph
from noodle.sdk import NodeRegistry, node
from noodle.sdk import registry as builtin_registry

workflow_registry = NodeRegistry()


def _filtered_kwargs(node_type, kwargs):
    nd = builtin_registry.get(node_type)
    if not nd.accepts_var_keyword and nd.param_names:
        return {k: v for k, v in kwargs.items() if k in nd.param_names}
    return dict(kwargs)


def _call_builtin(node_type, **kwargs):
    return builtin_registry.get(node_type).func(**_filtered_kwargs(node_type, kwargs))


async def _call_builtin_async(node_type, **kwargs):
    return await builtin_registry.get(node_type).func(
        **_filtered_kwargs(node_type, kwargs)
    )
'''

_FOOTER_TEMPLATE = '''

_DELEGATES = __DELEGATES__

_NODE_SETTINGS = __NODE_SETTINGS__

_PARAM_OVERRIDES = __PARAM_OVERRIDES__

_EXTRA_NODES = __EXTRA_NODES__

_EXTRA_EDGES = __EXTRA_EDGES__

# Sub-workflows referenced by execute_workflow / map_* nodes, bundled at
# export time and resolved locally — no Noodle server required.
SUBWORKFLOWS = __SUBWORKFLOWS__

ROOT_ID = __ROOT_ID__

_TRIGGER_TYPES = (
    "manual_trigger", "webhook_trigger", "api_endpoint",
    "schedule_trigger", "chat_trigger",
)


def _build_graph():
    """Reassemble the workflow graph from the decorated functions above."""
    nodes, edges, seq = [], [], 0
    for nd in workflow_registry._nodes.values():  # noqa: SLF001
        input_ports = {p.name for p in nd.manifest.inputs}
        params = {}
        for pname, p in inspect.signature(nd.func).parameters.items():
            if pname in input_ports:
                continue
            if p.default is not inspect.Parameter.empty:
                params[pname] = p.default
        params.update(_PARAM_OVERRIDES.get(nd.declared_id, {}))
        spec = {
            "id": nd.declared_id,
            "type": _DELEGATES.get(nd.declared_id, nd.manifest.id),
            "params": params,
        }
        spec.update(_NODE_SETTINGS.get(nd.declared_id, {}))
        nodes.append(spec)
        for port, wire in nd.wires.items():
            source, _, output = wire.partition(".")
            edges.append(
                {
                    "id": f"w{seq}",
                    "source": source,
                    "source_output": output or "main",
                    "target": nd.declared_id,
                    "target_input": port,
                }
            )
            seq += 1
    nodes.extend(_EXTRA_NODES)
    edges.extend(_EXTRA_EDGES)
    return {"nodes": nodes, "edges": edges}


def _runtime_registry():
    """Built-ins plus any hand-written custom nodes (ids not in _DELEGATES)."""
    merged = NodeRegistry()
    merged._nodes.update(builtin_registry._nodes)  # noqa: SLF001
    for nd in workflow_registry._nodes.values():  # noqa: SLF001
        if nd.declared_id not in _DELEGATES:
            merged._nodes[nd.manifest.id] = nd  # noqa: SLF001
    return merged


def _seed_trigger(graph, value):
    for spec in graph.get("nodes", []):
        node_type = str(spec.get("type") or "")
        if node_type in _TRIGGER_TYPES or node_type.endswith("_trigger"):
            return {spec["id"]: {"main": value if value is not None else {}}}
    return None


async def _run_subworkflow(call):
    graph = SUBWORKFLOWS.get(call.workflow_id)
    if graph is None:
        raise RuntimeError(
            f"sub-workflow \'{call.workflow_id}\' is not bundled in this export"
        )
    return InlineSubworkflow(
        graph=graph,
        cache=_seed_trigger(graph, call.parameters),
        targets=None,
        sources=tuple(str(e.get("source")) for e in graph.get("edges", [])),
    )


def main() -> None:
    meta = SubworkflowMeta(call_chain=frozenset({ROOT_ID} if ROOT_ID else ()))
    result = run(
        WorkflowGraph.model_validate(_build_graph()),
        _runtime_registry(),
        subworkflow_runner=_run_subworkflow,
        subworkflow_meta=meta,
    )
    print(f"workflow finished: {result.status}")
    for node_id, node_result in result.nodes.items():
        print(f"  {node_id}: {node_result.status}")
        if node_result.error:
            print(f"    error: {node_result.error}")


if __name__ == "__main__":
    main()
'''


def _identifier(node_id: str, used: set) -> str:
    base = re.sub(r"\W", "_", node_id) or "node_fn"
    if base[0].isdigit() or keyword.iskeyword(base):
        base = f"n_{base}"
    ident = base
    suffix = 2
    while ident in used:
        ident = f"{base}_{suffix}"
        suffix += 1
    used.add(ident)
    return ident


def _instance_settings(graph_node: GraphNode) -> dict:
    """GraphNode fields that differ from defaults (position, on_error, ...)."""
    dumped = graph_node.model_dump(exclude={"id", "type", "params"})
    return {
        key: value
        for key, value in dumped.items()
        if value != _DEFAULT_NODE_FIELDS.get(key)
    }


def workflow_to_module(
    graph: WorkflowGraph,
    name: str,
    *,
    registry,
    subworkflows: dict | None = None,
    root_id: str | None = None,
) -> str:
    """Render a workflow graph as a code-first Python module.

    ``registry`` is the live node registry (``noodle.sdk.registry`` with
    ``noodle_nodes`` imported) used to look up manifests, input ports, and
    async-ness for each node type.
    """
    delegates: dict = {}
    node_settings: dict = {}
    param_overrides: dict = {}
    extra_nodes: list = []
    # Each entry is (node_id, block_text) for wires injection.
    block_pairs: list = []
    used_idents: set = set()
    decorated_ids: set = set()

    for graph_node in graph.nodes:
        if graph_node.type not in registry:
            extra_nodes.append(graph_node.model_dump())
            continue
        node_def = registry.get(graph_node.type)
        manifest = node_def.manifest
        decorated_ids.add(graph_node.id)
        delegates[graph_node.id] = graph_node.type

        settings = _instance_settings(graph_node)
        if settings:
            node_settings[graph_node.id] = settings

        # Required manifest params (manifest defaults) overlaid with the
        # instance's configured params.
        params: dict = {}
        for spec in manifest.params:
            if spec.required:
                params[spec.name] = spec.default
        params.update(graph_node.params or {})

        signature_params: dict = {}
        overrides: dict = {}
        for pname, value in params.items():
            if pname.isidentifier() and not keyword.iskeyword(pname):
                signature_params[pname] = value
            else:
                overrides[pname] = value
        if overrides:
            param_overrides[graph_node.id] = overrides

        input_ports = [p.name for p in manifest.inputs]
        output_ports = [p.name for p in manifest.outputs]
        ident = _identifier(graph_node.id, used_idents)

        sig_parts = [f"{port}=None" for port in input_ports]
        sig_parts += [f"{k}={v!r}" for k, v in signature_params.items()]
        forward_parts = [f"{n}={n}" for n in [*input_ports, *signature_params]]

        is_async = node_def.is_async
        def_kw = "async def" if is_async else "def"
        call = "_call_builtin_async" if is_async else "_call_builtin"
        ret = "return await" if is_async else "return"
        label = graph_node.label or manifest.name

        block = (
            "@node(\n"
            f"    name={label!r},\n"
            f"    id={graph_node.id!r},\n"
            '    category="Exported",\n'
            f"    role={manifest.role.value!r},\n"
            f"    inputs={input_ports!r},\n"
            f"    outputs={output_ports!r},\n"
            "    wires={},\n"
            "    registry=workflow_registry,\n"
            ")\n"
            f"{def_kw} {ident}({', '.join(sig_parts)}):\n"
            f"    \"\"\"{graph_node.type} node from the Noodle workflow.\"\"\"\n"
            f"    {ret} {call}({graph_node.type!r}"
            + (", " + ", ".join(forward_parts) if forward_parts else "")
            + ")\n"
        )
        block_pairs.append((graph_node.id, block))

    # Edges: first edge per (target, input port) -> wires; the rest (and any
    # edge touching an _EXTRA_NODES node) -> _EXTRA_EDGES.
    wires_by_target: dict = {}
    extra_edges: list = []
    for edge in graph.edges:
        wire_value = (
            edge.source
            if edge.source_output in ("", "main")
            else f"{edge.source}.{edge.source_output}"
        )
        target_wires = wires_by_target.setdefault(edge.target, {})
        if edge.target in decorated_ids and edge.target_input not in target_wires:
            target_wires[edge.target_input] = wire_value
        else:
            extra_edges.append(edge.model_dump())

    # Inject wires into the generated decorator blocks.
    finished_blocks: list = []
    for node_id, block in block_pairs:
        wires = wires_by_target.get(node_id, {})
        block = block.replace("    wires={},\n", f"    wires={wires!r},\n")
        finished_blocks.append(block)

    header = _HEADER_TEMPLATE.replace("__NAME__", name).replace(
        "__SLUG__", slugify(name)
    )
    footer = (
        _FOOTER_TEMPLATE.replace("__DELEGATES__", repr(delegates))
        .replace("__NODE_SETTINGS__", repr(node_settings))
        .replace("__PARAM_OVERRIDES__", repr(param_overrides))
        .replace("__EXTRA_NODES__", repr(extra_nodes))
        .replace("__EXTRA_EDGES__", repr(extra_edges))
        .replace("__SUBWORKFLOWS__", json.dumps(subworkflows or {}, indent=2))
        .replace("__ROOT_ID__", repr(root_id))
    )
    return header + "\n\n" + "\n\n".join(finished_blocks) + footer
