"""Generate standalone artifacts from a workflow graph.

* :func:`workflow_to_script` emits a runnable ``.py`` file (library mode — it
  imports the ``nodyra`` runtime).
* :func:`docker_bundle` emits the files needed to ship the workflow as an image.
"""

import json
import pprint
import re

_SCRIPT_TEMPLATE = '''"""Nodyra workflow: __NAME__

Generated by Nodyra. Run with:  python __SLUG__.py
Requires: nodyra-core and nodyra-nodes (plus your environment packages).
"""

import os
import uuid
from pathlib import Path

import nodyra_nodes  # noqa: F401 - registers the built-in nodes
from nodyra.artifacts import LocalArtifactStore
from nodyra.context import artifact_store
from nodyra.engine import run
from nodyra.engine.subworkflows import InlineSubworkflow, SubworkflowMeta
from nodyra.models import WorkflowGraph
from nodyra.sdk import registry

GRAPH = __GRAPH__

# Sub-workflows referenced by execute_workflow / map_* nodes, bundled at
# export time and resolved locally — no Nodyra server required.
SUBWORKFLOWS = __SUBWORKFLOWS__

ROOT_ID = __ROOT_ID__

_TRIGGER_TYPES = (
    "manual_trigger", "webhook_trigger", "api_endpoint",
    "schedule_trigger", "chat_trigger",
)


def _seed_trigger(graph, value):
    for node in graph.get("nodes", []):
        node_type = str(node.get("type") or "")
        if node_type in _TRIGGER_TYPES or node_type.endswith("_trigger"):
            return {node["id"]: {"main": value if value is not None else {}}}
    return None


async def _run_subworkflow(call):
    graph = SUBWORKFLOWS.get(call.workflow_id)
    if graph is None:
        raise RuntimeError(
            f"sub-workflow '{call.workflow_id}' is not bundled in this export"
        )
    return InlineSubworkflow(
        graph=graph,
        cache=_seed_trigger(graph, call.parameters),
        targets=None,
        sources=tuple(
            str(e.get("source")) for e in graph.get("edges", [])
        ),
    )


def main() -> None:
    # Nodes that emit datasets or files need somewhere to put them. Without a
    # store they fail with "datasets are not available in this execution
    # context", which is most of the interesting ones. Override the location
    # with NODYRA_ARTIFACTS_DIR.
    here = Path(globals().get("__file__") or "workflow.py").resolve().parent
    artifacts_dir = Path(os.environ.get("NODYRA_ARTIFACTS_DIR") or here / "artifacts")
    store = LocalArtifactStore(artifacts_dir, run_id=uuid.uuid4().hex)
    token = artifact_store.set(store)
    try:
        meta = SubworkflowMeta(call_chain=frozenset({ROOT_ID} if ROOT_ID else ()))
        result = run(
            WorkflowGraph.model_validate(GRAPH),
            registry,
            subworkflow_runner=_run_subworkflow,
            subworkflow_meta=meta,
        )
    finally:
        artifact_store.reset(token)
    print(f"workflow finished: {result.status}")
    for node_id, node in result.nodes.items():
        print(f"  {node_id}: {node.status}")
        if node.error:
            print(f"    error: {node.error}")


if __name__ == "__main__":
    main()
'''

_DOCKERFILE_TEMPLATE = """FROM python:__PYVER__-slim

WORKDIR /workflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY workflow.py .

CMD ["python", "workflow.py"]
"""

_README_TEMPLATE = """# __NAME__

A Nodyra workflow packaged as a Docker image.

```sh
docker build -t __SLUG__ .
docker run --rm __SLUG__
```
"""


def slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "workflow"


def _python_literal(value: object) -> str:
    """Render ``value`` as a Python literal the generated script can evaluate.

    ``json.dumps`` is not safe here: it emits ``null``/``true``/``false``,
    which are not Python. ``pprint`` renders the same data as ``None``/``True``
    /``False`` and keeps the nesting readable.
    """
    return pprint.pformat(value, indent=2, width=88, sort_dicts=False)


def workflow_to_script(
    graph: dict,
    name: str,
    *,
    subworkflows: dict[str, dict] | None = None,
    root_id: str | None = None,
) -> str:
    """Render a workflow graph as a standalone Python script.

    ``subworkflows`` maps workflow id → graph for every workflow reachable
    through execute_workflow / map_* params; they run locally via the
    engine's inline-subworkflow directive. ``root_id`` seeds the call chain
    so a bundled child calling back into the root is caught as a cycle.
    """
    # The graph is embedded as a Python literal, not as JSON. A serialized
    # node carries "label": null and "disabled": false, and JSON spells those
    # null/false/true — which Python reads as undefined names, so the exported
    # script died on import with NameError before running a single node.
    return (
        _SCRIPT_TEMPLATE.replace("__NAME__", name)
        .replace("__SLUG__", slugify(name))
        .replace("__GRAPH__", _python_literal(graph))
        .replace("__SUBWORKFLOWS__", _python_literal(subworkflows or {}))
        .replace("__ROOT_ID__", repr(root_id))
    )


def docker_bundle(
    graph: dict,
    name: str,
    *,
    python_version: str = "3.12",
    packages: list[str] | None = None,
    subworkflows: dict[str, dict] | None = None,
    root_id: str | None = None,
) -> dict[str, str]:
    """Render the file set needed to build and run the workflow as an image."""
    requirements = ["nodyra-core", "nodyra-nodes", *(packages or [])]
    return {
        "workflow.py": workflow_to_script(
            graph, name, subworkflows=subworkflows, root_id=root_id
        ),
        "requirements.txt": "\n".join(requirements) + "\n",
        "Dockerfile": _DOCKERFILE_TEMPLATE.replace("__PYVER__", python_version),
        "README.md": _README_TEMPLATE.replace("__NAME__", name).replace(
            "__SLUG__", slugify(name)
        ),
    }
