"""Create a persistent, loopback-only environment file for ``make demo``."""

from __future__ import annotations

import argparse
import os
import secrets
import string
import tempfile
from pathlib import Path

_ALPHANUMERIC = string.ascii_letters + string.digits
_REQUIRED_KEYS = {
    "AUTH_REQUIRED",
    "DATABASE_URL",
    "INTERNAL_API_TOKEN",
    "MINIO_ROOT_PASSWORD",
    "NODYRA_BIND_HOST",
    "NODYRA_MCP_URL",
    "NODYRA_SECRET_KEY",
    "POSTGRES_PASSWORD",
    "SECRET_KEY",
}
_LOOPBACK_HOSTS = {"127.0.0.1", "::1", "localhost"}


def _secret(length: int = 48) -> str:
    return "".join(secrets.choice(_ALPHANUMERIC) for _ in range(length))


def generated_values() -> dict[str, str]:
    postgres_password = _secret()
    secret_key = _secret(64)
    return {
        "COMPOSE_PROJECT_NAME": "nodyra-demo",
        "NODYRA_BIND_HOST": "127.0.0.1",
        "POSTGRES_PASSWORD": postgres_password,
        "MINIO_ROOT_USER": "nodyra",
        "MINIO_ROOT_PASSWORD": _secret(),
        "INTERNAL_API_TOKEN": _secret(64),
        "NODYRA_SECRET_KEY": secret_key,
        # The seed script runs on the host and reads the unprefixed setting.
        "SECRET_KEY": secret_key,
        "AUTH_REQUIRED": "false",
        "AUTH_ALLOW_REGISTRATION": "false",
        "DATABASE_URL": (
            "postgresql+asyncpg://nodyra:"
            f"{postgres_password}@127.0.0.1:5432/nodyra"
        ),
        "NODYRA_MCP_URL": "http://127.0.0.1:8000/mcp",
    }


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{path}:{line_number}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in values:
            raise ValueError(f"{path}:{line_number}: invalid or duplicate key")
        values[key] = value.strip()
    return values


def validate_values(values: dict[str, str], *, source: Path) -> None:
    missing = sorted(key for key in _REQUIRED_KEYS if not values.get(key))
    if missing:
        raise ValueError(f"{source}: missing required keys: {', '.join(missing)}")
    if values["NODYRA_BIND_HOST"].lower() not in _LOOPBACK_HOSTS:
        raise ValueError(
            f"{source}: make demo must remain loopback-only; use a normal "
            "authenticated deployment for network access"
        )
    if values["AUTH_REQUIRED"].lower() != "false":
        raise ValueError(
            f"{source}: make demo requires AUTH_REQUIRED=false and loopback binding"
        )
    for key, minimum in (
        ("POSTGRES_PASSWORD", 32),
        ("MINIO_ROOT_PASSWORD", 32),
        ("INTERNAL_API_TOKEN", 32),
        ("NODYRA_SECRET_KEY", 32),
        ("SECRET_KEY", 32),
    ):
        if len(values[key]) < minimum:
            raise ValueError(f"{source}: {key} must contain at least {minimum} characters")


def _render(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/generate_demo_env.py.",
        "# Local demo only. Do not reuse these credentials in production.",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def ensure_demo_env(path: Path, *, force: bool = False) -> bool:
    """Ensure a valid demo env exists; return True when a new file was written."""
    expanded_path = path.expanduser()
    if expanded_path.is_symlink():
        raise ValueError(f"Refusing to write demo secrets through symlink: {expanded_path}")
    path = expanded_path.resolve()
    if path.exists() and not force:
        validate_values(parse_env_file(path), source=path)
        try:
            path.chmod(0o600)
        except OSError:
            pass
        return False

    values = generated_values()
    validate_values(values, source=path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent, text=True
    )
    temporary_path = Path(temporary_name)
    try:
        os.chmod(temporary_path, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(_render(values))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
        try:
            path.chmod(0o600)
        except OSError:
            pass
    except BaseException:
        try:
            os.close(fd)
        except OSError:
            pass
        temporary_path.unlink(missing_ok=True)
        raise
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(".tmp/nodyra-demo.env"))
    parser.add_argument(
        "--force", action="store_true", help="rotate every generated demo credential"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        created = ensure_demo_env(args.output, force=args.force)
    except (OSError, ValueError) as exc:
        raise SystemExit(f"Unable to prepare demo environment: {exc}") from exc
    action = "Created" if created else "Reusing"
    print(f"{action} demo environment at {args.output} (secret values hidden).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
